services:
  hashkorea:
    image: ${DOCKER_REGISTRY-}hashkorea
    build:
      context: .
      dockerfile: HashKorea/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./app-data:/app/data 