services:
  hashkorea:
    image: ${DOCKER_REGISTRY-}hashkorea
    env_file: .env
    container_name: hashkorea.full
    build:
      context: .
      dockerfile: HashKorea/Dockerfile
    ports:
      - "8080:8080"
    environment:
      # - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=${AWS_SERVER};Port=3306;Database=${AWS_DATABASE};User=${AWS_USER};Password=${AWS_PASSWORD};
    volumes:
      - ./uploads:/app/uploads
      - ~/.aws:/root/.aws:ro
    user: "${UID}:${GID}"